Test new model: Update withdraw liquidity test
alpha-fi/clp-contracts pull request #89
Opened 2021-04-15 03:33 UTC by amityadav0

2021-04-15 21:29 UTC, robert-zaremba commented on nearswap/src/lib.rs
> +        _init(NDENOM * 120)
why we are charging 120 NAER here?

2021-04-15 21:29 UTC, robert-zaremba commented on nearswap/src/lib.rs
> +        let ynear_deposit_with_storage = ynear_deposit + NDENOM;
1 NEAR is a lot here.

2021-04-19 07:19 UTC, amityadav0 commented on nearswap/src/lib.rs
> +        let ynear_deposit_with_storage = ynear_deposit + NDENOM;
yes decreasing

2021-04-19 07:19 UTC, amityadav0 commented on nearswap/src/lib.rs
> +        _init(NDENOM * 120)
decreasing

2021-04-22 07:56 UTC, robert-zaremba requested changes
It seams that we are missing tests for failures.

2021-04-22 18:43 UTC, amityadav0 commented
Added

2021-04-26 19:54 UTC, robert-zaremba approved these changes

2021-04-27 05:08 UTC, merged